---
# Install VirtualBox on Fedora

- name: VIRTUALBOX | Setup VirtualBox yum repository on Fedora
  yum_repository:
    name: virtualbox
    description: Fedora $releasever - $basearch - VirtualBox
    baseurl: >-
      http://download.virtualbox.org/virtualbox/rpm/fedora/
      {{ ansible_facts['distribution_major_version'] }}/$basearch
    enabled: 1
    gpgcheck: 1
    repo_gpgcheck: 1
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
  become: true

- name: VIRTUALBOX | Install VirtualBox
  yum:
    name: "VirtualBox-{{ virtualbox_version }}.{{ ansible_architecture }}"
    state: present
  become: true

- name: VIRTUALBOX | Install VirtualBox vboxdrv requirements on Fedora
  yum:
    name: "{{ vboxdrv_required_packages_fedora34 }}"
    state: present
  register: vboxdrv_is_installed_command
  become: true

- name: VIRTUALBOX | Start & enable vboxdrv service
  service:
    name: vboxdrv
    state: started
    enabled: true
  when: vboxdrv_is_installed_command.changed
  become: true
